### ISSUE TITLE
"Просьба проверить домашнее задание" 

### ISSUE THREAD

**Issue by EvgenyTernovoy** [EvgenyTernovoy/typing-practice#1]

**Comment by EvgenyTernovoy** [comment]
Код в ветке[ hm_typing ](https://github.com/EvgenyTernovoy/typing-practice/tree/hm_typing)

**Comment by EvgenyTernovoy** [comment]
Не придумал, как [здесь](https://github.com/EvgenyTernovoy/typing-practice/blob/29a34f5918e0ed41241194b987f76144d5400409/src/services/user-service.ts#L43) реализовать доказательство, что текущий пользователь имеет доступ к определенным операциям над другим пользователем. Хотел сделать через type guard, но что-то не понравилось это решение из за его громоздкости. Подскажите, как еще это можно сделать.

**Comment by JSMonk** [comment]
Здравствуйте, Евгений.
Попробуейте посмотреть в эту сторону (главное, посмотрите внимательно на типы): https://www.typescriptlang.org/play?#code/MYewdgzgLgBApmArgWxgVQnAThGBvAKBmPQGUBRAJQH0BBAGiJLQpoCECBfAg0SWBChgB5AA7YAhlACW4XIRIiAClVoAVAJLCAcnUaLhKyuq262jbrzmxaANVoaAMrTaPy1AMI6AYhoDiaMaaOjAAvPhMxADaGNgQAHQsVHQAugBcMFFikjJy8Yaqwbq0KfokMZg4iazUbOmZ2VhSspD5RiY6eiLiTbmtBUGmtaVcMBK4fNAA3DxQAJ7iMHYOzq7uXtq+AYMh4fPiIABmS-ZOLm6ePv6BHdozBIeIYMB9MADmcFC0AG4S0gA2EgARv84I1mnIADxoeAADygCAAJrhYjgAHwACkQlQyaAAlBllmc1pdNtcdtoYikIoosJ9EFgwCcVud1ldtrcotjsCkZpZJrAQD0IZBvCAsLQwu9Pj8-oCQWDhX0IBjUQkkjRaHipkA

**Comment by JSMonk** [comment]
По поводу других нюансов:
1. Не совсем понимаю надобность выделение `User | null` в отдельный тип [здесь](https://github.com/JSMonk/typing-practice/compare/homework-task...EvgenyTernovoy:hm_typing#diff-bac620025b1ea1d4e682e02c6686175878cde2ff3c92297dd2c3f4f769c100dfR7).
2. У Вас нет проверки ни на правильность эмейла, ни на то, что это пустая строка (мы не зря написали [здесь](https://github.com/JSMonk/typing-practice/compare/homework-task...EvgenyTernovoy:hm_typing#diff-586fbcdbd6547954463562f3e9b420c6296b700ddacc6daf81634f4c51a8756cR9) указать более точные типы).

**Comment by EvgenyTernovoy** [comment]
Спасибо за фидбэк.

Поправил код для [getAvailableOperations](https://github.com/EvgenyTernovoy/typing-practice/blob/714a4acf3000adf2223fabe8189dc4bed5b664ff/src/services/user-service.ts#L39)

1. Кажется, что можно забыть для currentUser указать null ` User | null `. Или все же это излишне, выделять это в отдельный тип?

2. Указал более конкретный тип для поля [email](https://github.com/EvgenyTernovoy/typing-practice/blob/714a4acf3000adf2223fabe8189dc4bed5b664ff/src/hooks/use-login.ts#L9), и добавил [валидацию](https://github.com/EvgenyTernovoy/typing-practice/blob/714a4acf3000adf2223fabe8189dc4bed5b664ff/src/services/login-service.ts#L9). Этого достаточно или нужно как-то более хитро?

**Comment by JSMonk** [comment]
Здравствуйте, Евгений.
1. Помните про DSL на типах? Мы пытались объявить конфигурацию на уровне типа. Посмотрите на [вот этот пример](https://www.typescriptlang.org/play?#code/MYewdgzgLgBApmArgWxgVQnAThGBvAKBmPQGUBRAJQH0BBAGiJLQpoCECBfAg0SWBChgB5AA7YAhlACW4XIRIiAClVoAVAJLCAcnUaLhKyuq262jbrzmxaANVoaAMrTaPy1AMI6AYhoDiaMaaOjAAvPhMxADaGNgQAHQsVHQAugBcMFFikjJy8Yaqwbq0KfokMZg4iazUbOmZ2VhSspD5RiY6eiLiTbmtBUGmtaVcMBK4fNAA3DxQAJ7iMHYOzq7uXtq+AYMh4fPiIABmS-ZOLm6ePv6BHdozBIeIYMB9MADmcFC0AG4S0gA2EgARv84I1mnIADxoeAADygCAAJrhYjgAHwACkQlQyaAAlBllmc1pdNtcdtoYikIoosJ9EFgwCcVud1ldtrcotjsCkZpZJrAQD0IZBvCAsLQwu9Pj8-oCQWDhX0IBjUQkkuw8VMgA) и попытайтесь описать Вашу бизнес-логику на уровне типа.
2. Кажется, это излишне, так как нужно будет идти в определение типа, что бы понять, что функция иногда возвращает  `null`.
3. Нужно чуть более хитро, так как у Вас все равно можно передать пароль как пустую строку, или `email` как "@.". Давайте попробуем выделить более строгие типы, как мы делали [здесь](https://github.com/EvgenyTernovoy/typing-practice/blob/714a4acf3000adf2223fabe8189dc4bed5b664ff/src/entities/moderator.ts#L5)

**Comment by EvgenyTernovoy** [comment]
Здравствуйте, Артем. 

1. Хм, вроде я реализовал логику, как в примере вот [здесь](https://github.com/EvgenyTernovoy/typing-practice/blob/714a4acf3000adf2223fabe8189dc4bed5b664ff/src/services/user-service.ts#L48). Или я что-то сделал не так. Не совсем понимаю в чем отличие.

**Comment by EvgenyTernovoy** [comment]
Здравствуйте, Артем. 

Подскажите правильно ли я мыслю.

1. Бизнес сущности я описываю в этом  [файле](https://github.com/EvgenyTernovoy/typing-practice/blob/df857f252dc97b76842163f0e3e06301e73ff92d/src/entities/available-user-operations-type.ts) (DSL на типах), что дает нам документируемость бизнес сущностей. 

Затем, используя эти типы мы можем доказать, что конкретный пользователь может иметь только конкретные операции над определенным пользователем. Это доказательство я реализую следующим образом:
`getOperations<CU extends User, U extends User> (currentUser: CU, user: U): AVAILABLE_USER_OPERATIONS_TYPE[CU['role']][U['role']]`

Но нам этого не достаточно, так как мы еще должны добавить строгости при передачи пользователей. Это я реализую [здесь](https://github.com/EvgenyTernovoy/typing-practice/blob/df857f252dc97b76842163f0e3e06301e73ff92d/src/services/user-service.ts#L74).
Плюс нужно добавить проверки в рантайме с помощью тайп гвардов которые я реализовал [таким образом](https://github.com/EvgenyTernovoy/typing-practice/blob/df857f252dc97b76842163f0e3e06301e73ff92d/src/services/user-service.ts#L51).

Есть в этом во всем момент который меня смущает, это количество кода. Для каждой пары currentUser - User мы должны написать отдельную функцию типа  
`private getOperationsForAdminOverModerator<CU extends Admin, U extends Moderator> (currentUser: CU, user: U): AVAILABLE_USER_OPERATIONS_TYPE[CU['role']][U['role']] {
    return AVAILABLE_USER_OPERATIONS[currentUser.role][user.role]
  }`. 
  При этом если у нас будет большее количество типов пользователей то количество подобного кода сильно возрастет. Отсюда возникают вопросы, правильный ли это подход и можно ли как-то это улучшить?

**Comment by JSMonk** [comment]
Здравствуйте, Евгений.
В целом, у нас уже и так делаются проверки для юзеров, так что гварды можно убрать и [оставить `getAvailableOperations` так](
https://www.typescriptlang.org/play?ssl=39&ssc=12&pln=24&pc=6#code/MYewdgzgLgBApmArgWxgJRAGzjA3jAQQBEBZASQDkYAaGEgeSIFE0CAVetWgYQBkymFNjAC+AKFCRYCFDHoAHOACcAhlACW4PDACqABSLsmAfQ7G+AoTV0Gjp+sYbNWHLjcNsTZ4uSriJmCoQEIQAJsjqYHhiMLEw8krqAG5qOEpwKqHgmACeMMZQOYowALwwAMo5yABGWAAUAEQE4ZENAJQA3DFx6ZnZeUpYOGUY2AB0PpRd-sCBwXQgocpqIErRcfGJKVBpGVlgufmFxWWVNfUNJIvLUKvtXRu9+4eD2KXoQ2NOLOyc02IBIIhbiYdQIWC4bqxBLJVIwJ79I5FYYVKq1TCNEFgsBQe5Q+F7RGvFGjOBjCyCNj-MTHHA6CDKd7NCJRAA+MCx4Jg7KuS1UtyUXVpMD0W3U2AA5nBQvTGWVmZFuQs+StBQCAPTqmCAHBBAHwggDYQQC8ILqYIBREEAAiCABhBDYAOEEAQiCAGRAYIAuEEtzpgurtgBYQQCsIIBuEAdhsAwiCAORAXbrDYAREBtgGYQINWwBiIDaw4AmEBdbt1gB4QAC0dpNkctgE4QP0+iTgaCEABqBDIvAIACFeCZ6HofmwyPQKOV3pCNgBtUnk-iUgC6AC51hs4gPPpMKOOYH2R9R8f3B98XJwF0uV1Pp4OKUJtyP8SJd-vPhvfmgF7294vB3Pj+e9zPxlfXNuFDdNGAxvoPC8BxDzYZdVwvcYQK-RR+V-f9bE8exHEYNst1PF8H1nUhKFvcDYjfMknwnPtv1g8B4MApCPy3DC10vFDNxvYjSLUOCALsMwQNoFiNHI9jEO8bD51oiCySg5iYNYviEKA5DnGvE8NnEEQYCCGBJGgLoaWRKsazrRtm1bFwOy7d5aRAAAzXTawbJtjBbNsTPKLSLMQMBgF4qIpSgAgUnFFRqmwHjfwgAAefE0AARngAAPHYwFCEJSVofEdGiuA4oQRLdAZNYADJtGJCcotEDC0AAJli+LsuS1LKoy6qQlFZJxTgKUZVymACvwIr0Eqs8xAAPjqRBconNLaGARAlHSHFZSUcbyraSd0igaaogIasbIM+yjPYJy+ymmbwXmsZiRHPtRuUM6hhHVSQk2vTbMMxzO3KPsdHKvsGmJBoRwutLvt+-7qVc9zPJgK7gvAUK0qqrKQnm2hPvhhKmrFSVpXm4aroW3RIsm6bZqgebFuWu9VvWmBvN8lR-MCuBocgEbcsJ465tyzoxH8TUYEABBAYDtIM7RgIN9R9GBDQlzNLUAfhBZftQBBEEAeRBw3Nc0fWdO1jQlwB2EENS1AHEQH1bQllNdV1lMrUASRBLR9TNdRjE1nV1c07R9fVLTGGBAHwQc0bVNXUvSV1WFcVy1HQ9QBGEF1KPrcARRBDUNQBpEELQWbVl72yykVT3ihyTPLqMA4AAd2VG5VjqNpaGLsuFTAKuuaAA.)
Потому что Мы уже гарантировали, что у нас будет на входе какой-то юзер (а не просто объект, и уже все было проверенно до вызова функции `getAvailableOperations`.

**Comment by EvgenyTernovoy** [comment]
@JSMonk Внес правки:

1. [Валидация логина](https://github.com/EvgenyTernovoy/typing-practice/blob/2402abf23c51302c93d5c727fdbde67015203576/src/hooks/use-login.ts#L21)

2. [getAvailableOperations](https://github.com/EvgenyTernovoy/typing-practice/blob/2402abf23c51302c93d5c727fdbde67015203576/src/services/user-service.ts#L38)

Не совсем понятно несколько моментов. Почему мы в дженерике указываем 4 параметра, в то время как в функции ожидается 2.
```
getAvailableOperations<
    R1 extends Role,
    U1 extends User & { role: R1 },
    R2 extends Role,
    U2 extends PrivilegedUser & { role: R2 },
    >(user: U1, currentUser: U2);
```
 И для чего мы указываем такую штуку `
U1 extends User & { role: R1 }` Вроде как в самом объекте User у нас уже присутствует поле role?

**Comment by JSMonk** [comment]
Здравствуйте, Евгений.
По поводу 4 параметров - осталось от функции, где не использовал `U1['role']`.

Давайте [вот здесь](https://github.com/JSMonk/typing-practice/compare/homework-task...EvgenyTernovoy:hm_typing#diff-586fbcdbd6547954463562f3e9b420c6296b700ddacc6daf81634f4c51a8756cR32) будем кидать исключение.
А [вот здесь](https://github.com/JSMonk/typing-practice/compare/homework-task...EvgenyTernovoy:hm_typing#diff-586fbcdbd6547954463562f3e9b420c6296b700ddacc6daf81634f4c51a8756cR35) теряется весь смысл `opaque` типов, так как Вы можете создать значение для этого типа вне модуля его определения))

**Comment by EvgenyTernovoy** [comment]
@JSMonk поправил.

**Comment by JSMonk** [comment]
Гуд, принято.
P.S. Не связанный никак с типами suggestion, но [вот здесь](https://github.com/JSMonk/typing-practice/compare/homework-task...EvgenyTernovoy:hm_typing#diff-586fbcdbd6547954463562f3e9b420c6296b700ddacc6daf81634f4c51a8756cR16) можно `find` использовать + кажется, данная логика лучше будет смотреться в `UserService`.
